version: "2.1"

networks:
  test:

services:
  onlineBank_db:
    image: mysql:5.7.27
    container_name: onlineBank_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=onlinebanking
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./sql_dump/onlinebanking.sql:/docker-entrypoint-initdb.d/0_init.sql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U db_user -P 123456 -Q "SELECT 1 FROM onlinebanking" || exit 1
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - test
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      onlineBank_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - test
    command: java -jar /Online-Bank-Simulator/target/userFront-0.0.1-SNAPSHOT.jar

